#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
dlink,dsp-w215)
	# Green status LED on when associated to Wi-Fi (client) or running.
	ucidef_set_led_netdev "wifi" "WIFI" "green:status" "wlan0"
	;;
esac

board_config_flush

exit 0
